spring:
  datasource:
    url: jdbc:h2:mem:inventory_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Importante: NO usar DDL de Hibernate todavía
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: never     # por ahora no ejecutaremos schema.sql/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
